name: Docker workflow

on:
  push:
    branches:
      - main

jobs:

  github-registry:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: linux/amd64

      - name: Set up Docker Buildx
        id: build-opts
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        run: |-
          set -e
          docker buildx build $(cat .versions | sed 's@^@--build-arg @g ') \
            --tag ghcr.io/renanpalmeira/protobuf:latest \
            --target protobuf \
            --platform linux/amd64 \
            --file Dockerfile \
            --push .
